### PR TITLE
feat(i18n): Add german translation

### PR DESCRIPTION
**Pull request by zewa666**
feat(i18n): Add german translation

Adds the german translation

### CODE REVIEW

**Comment by sksbrg** [comment]
Hi zewa666, nice work! Seems I need to find another chance for contribution ;) May I suggest to use most commonly used "mindestens" instead of "zumindest"?

>'MinimumLengthValidationRule' : (newValue, threshold) => {
>   return `muss mindestens ${threshold} Zeichen lang sein`;
>},

>'StrongPasswordValidationRule' : (newValue, threshold) => {
>            if(threshold == 4)
>                return `sollte eine Kombination aus Groß- und Kleinbuchstaben, sowie Zahlen und Sonderzeichen enthalten`;
>            else
>                return `sollte mindestens ${threshold} der folgenden Gruppen enthalten: Kleinbuchstaben, Großbuchstaben, Zahlen oder Sonderzeichen`;
>        }

**Comment by zewa666** [comment]
good catch but actually its even more complicated :)
The first one should be `mindestens` as its a purely quantitative measure of the same entity, whereas the second should stay `zumindest` as you do a qualitative selection of multiple entities.

**Comment by sksbrg** [comment]
Yep, we have a favour for complicated language constructs :) Thanks for the explanation!

**Comment by janvanderhaegen** [comment]
German, why you so hardcore!

**Pull request merged**
